#
# Copyright 2017, Data 61
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

# Stackage LTS Haskell 9.21 (ghc-8.0.2)
resolver: lts-9.21

local-bin-path: .
